### PR TITLE
Sort LDM partitions by offset

### LINKED ISSUE #9: Windows span volume will not always have partition information in order
Windows span volume will not always have the partitions in the correct order
There's a bug around
https://github.com/mdbooth/libldm/blob/master/src/ldm.c#L2790
where it expects the partitions from `vol->parts` to be in sequential order

The partitions should be sorted by their `part->vol_offset` first before constructing the dm targets.

### PR DESCRIPTION
**Pull request by guysmoilov**
Fixes #9

### CODE REVIEW

**Comment by sodul** [comment]
@guysmoilov This PR is now obsolete.

**Comment by guysmoilov** [comment]
@sodul Not completely sure I understand the difference but  ¯\_(ツ)_/¯

**Comment by sodul** [comment]
> @sodul Not completely sure I understand the difference but ¯_(ツ)_/¯

Yes, @guysmoilov, that's pretty much your code but a little more explicit with comments. Our version was from @deepans-clumio, I was just passing along our custom version.

Thank you for making the original fix as it solved a real issue we were facing.

**Comment by guysmoilov** [comment]
Thanks, that credit goes to @Unmoon though. I just opened the PR with their code fix.

**Comment by deepans-clumio** [comment]
@guysmoilov @Unmoon Thank you for discovering the root case of the issue. and putting out a PR. I just changed the comparator to be more explicit and added some comments. Appreciate your help!

**Pull request closed without merging**
